// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"
)

const TableNameActor = "actor"

// Actor mapped from table <actor>
type Actor struct {
	ID          int32     `gorm:"column:ID;type:int;primaryKey;autoIncrement:true" json:"ID"`
	NAME        string    `gorm:"column:NAME;type:varchar(255)" json:"NAME"`
	CREATEDTIME time.Time `gorm:"column:CREATED_TIME;type:datetime" json:"CREATED_TIME"`
	UPDATEDTIME time.Time `gorm:"column:UPDATED_TIME;type:datetime" json:"UPDATED_TIME"`
}

// TableName Actor's table name
func (*Actor) TableName() string {
	return TableNameActor
}
