// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"
)

const TableNameAuthor = "author"

// Author mapped from table <author>
type Author struct {
	ID          int32     `gorm:"column:ID;type:int;primaryKey;autoIncrement:true" json:"ID"`
	NAME        string    `gorm:"column:NAME;type:varchar(255)" json:"NAME"`
	CREATEDTIME time.Time `gorm:"column:CREATED_TIME;type:datetime" json:"CREATED_TIME"`
	UPDATEDTIME time.Time `gorm:"column:UPDATED_TIME;type:datetime" json:"UPDATED_TIME"`
}

// TableName Author's table name
func (*Author) TableName() string {
	return TableNameAuthor
}
