// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNameEleTagRe = "ele_tag_re"

// EleTagRe mapped from table <ele_tag_re>
type EleTagRe struct {
	ID    int32 `gorm:"column:ID;type:int;primaryKey;autoIncrement:true" json:"ID"`
	ELEID int64 `gorm:"column:ELE_ID;type:bigint;not null" json:"ELE_ID"`
	TAGID int32 `gorm:"column:TAG_ID;type:int;not null" json:"TAG_ID"`
}

// TableName EleTagRe's table name
func (*EleTagRe) TableName() string {
	return TableNameEleTagRe
}
