// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

const TableNameEleActorRe = "ele_actor_re"

// EleActorRe mapped from table <ele_actor_re>
type EleActorRe struct {
	ID      int32 `gorm:"column:ID;type:int;primaryKey;autoIncrement:true" json:"ID"`
	ELEID   int64 `gorm:"column:ELE_ID;type:bigint;not null" json:"ELE_ID"`
	ACTORID int32 `gorm:"column:ACTOR_ID;type:int;not null" json:"ACTOR_ID"`
}

// TableName EleActorRe's table name
func (*EleActorRe) TableName() string {
	return TableNameEleActorRe
}
