// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package dao

import (
	"time"
)

const TableNameJav = "jav"

// Jav mapped from table <jav>
type Jav struct {
	ELEID       int64     `gorm:"column:ELE_ID;type:bigint;primaryKey" json:"ELE_ID"`
	CODE        string    `gorm:"column:CODE;type:varchar(64);primaryKey" json:"CODE"` // 識別碼
	TITLE       string    `gorm:"column:TITLE;type:varchar(255)" json:"TITLE"`
	PUBLISHDATE time.Time `gorm:"column:PUBLISH_DATE;type:datetime" json:"PUBLISH_DATE"` // 發行日期
	LENGTH      int32     `gorm:"column:LENGTH;type:int" json:"LENGTH"`                  // 長度
	DIRECTOR    string    `gorm:"column:DIRECTOR;type:varchar(255)" json:"DIRECTOR"`
	SERIES      string    `gorm:"column:SERIES;type:varchar(255)" json:"SERIES"`
	CreatedAt   time.Time `gorm:"column:CREATED_TIME;type:datetime" json:"CREATED_TIME"`
	UpdatedAt   time.Time `gorm:"column:UPDATED_TIME;type:datetime" json:"UPDATED_TIME"`
}

// TableName Jav's table name
func (*Jav) TableName() string {
	return TableNameJav
}
