// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"pelican/internal/dal/dao"
)

func newElement(db *gorm.DB) element {
	_element := element{}

	_element.elementDo.UseDB(db)
	_element.elementDo.UseModel(&dao.Element{})

	tableName := _element.elementDo.TableName()
	_element.ALL = field.NewAsterisk(tableName)
	_element.ID = field.NewInt64(tableName, "ID")
	_element.TYPE = field.NewString(tableName, "TYPE")
	_element.FILEDIR = field.NewString(tableName, "FILE_DIR")
	_element.FILESIZE = field.NewInt64(tableName, "FILE_SIZE")
	_element.SHAREDFLAG = field.NewInt32(tableName, "SHARED_FLAG")
	_element.PUBLISHEDFLAG = field.NewInt32(tableName, "PUBLISHED_FLAG")
	_element.UPLOADER = field.NewString(tableName, "UPLOADER")
	_element.AVAILABLEFLAG = field.NewInt32(tableName, "AVAILABLE_FLAG")
	_element.COMPLETEDFLAG = field.NewInt32(tableName, "COMPLETED_FLAG")
	_element.CreatedAt = field.NewTime(tableName, "CREATED_TIME")
	_element.UpdatedAt = field.NewTime(tableName, "UPDATED_TIME")
	_element.Ehentai_gallery = elementHasOneEhentai_gallery{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Ehentai_gallery", "dao.EhentaiGallery"),
	}

	_element.EleFile = elementHasManyEleFile{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("EleFile", "dao.EleFile"),
	}

	_element.Actor = elementManyToManyActor{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Actor", "dao.Actor"),
	}

	_element.Author = elementManyToManyAuthor{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Author", "dao.Author"),
	}

	_element.Organization = elementManyToManyOrganization{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("Organization", "dao.Organization"),
	}

	_element.TagInfo = elementManyToManyTagInfo{
		db: db.Session(&gorm.Session{}),

		RelationField: field.NewRelation("TagInfo", "dao.TagInfo"),
	}

	_element.fillFieldMap()

	return _element
}

type element struct {
	elementDo

	ALL             field.Asterisk
	ID              field.Int64
	TYPE            field.String
	FILEDIR         field.String // 关联文件所在目录
	FILESIZE        field.Int64  // 关联文件总大小，单位为 B
	SHAREDFLAG      field.Int32  // 分享标志(0-否;1-是)
	PUBLISHEDFLAG   field.Int32  // 释放标志(0-否;1-是)，释放后上传者将不能删除元素
	UPLOADER        field.String // 上传用户
	AVAILABLEFLAG   field.Int32  // 启用标志(0-禁用;1-启用)
	COMPLETEDFLAG   field.Int32  // 完成标志
	CreatedAt       field.Time
	UpdatedAt       field.Time
	Ehentai_gallery elementHasOneEhentai_gallery

	EleFile elementHasManyEleFile

	Actor elementManyToManyActor

	Author elementManyToManyAuthor

	Organization elementManyToManyOrganization

	TagInfo elementManyToManyTagInfo

	fieldMap map[string]field.Expr
}

func (e element) Table(newTableName string) *element {
	e.elementDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e element) As(alias string) *element {
	e.elementDo.DO = *(e.elementDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *element) updateTableName(table string) *element {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt64(table, "ID")
	e.TYPE = field.NewString(table, "TYPE")
	e.FILEDIR = field.NewString(table, "FILE_DIR")
	e.FILESIZE = field.NewInt64(table, "FILE_SIZE")
	e.SHAREDFLAG = field.NewInt32(table, "SHARED_FLAG")
	e.PUBLISHEDFLAG = field.NewInt32(table, "PUBLISHED_FLAG")
	e.UPLOADER = field.NewString(table, "UPLOADER")
	e.AVAILABLEFLAG = field.NewInt32(table, "AVAILABLE_FLAG")
	e.COMPLETEDFLAG = field.NewInt32(table, "COMPLETED_FLAG")
	e.CreatedAt = field.NewTime(table, "CREATED_TIME")
	e.UpdatedAt = field.NewTime(table, "UPDATED_TIME")

	e.fillFieldMap()

	return e
}

func (e *element) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *element) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 17)
	e.fieldMap["ID"] = e.ID
	e.fieldMap["TYPE"] = e.TYPE
	e.fieldMap["FILE_DIR"] = e.FILEDIR
	e.fieldMap["FILE_SIZE"] = e.FILESIZE
	e.fieldMap["SHARED_FLAG"] = e.SHAREDFLAG
	e.fieldMap["PUBLISHED_FLAG"] = e.PUBLISHEDFLAG
	e.fieldMap["UPLOADER"] = e.UPLOADER
	e.fieldMap["AVAILABLE_FLAG"] = e.AVAILABLEFLAG
	e.fieldMap["COMPLETED_FLAG"] = e.COMPLETEDFLAG
	e.fieldMap["CREATED_TIME"] = e.CreatedAt
	e.fieldMap["UPDATED_TIME"] = e.UpdatedAt

}

func (e element) clone(db *gorm.DB) element {
	e.elementDo.ReplaceDB(db)
	return e
}

type elementHasOneEhentai_gallery struct {
	db *gorm.DB

	field.RelationField
}

func (a elementHasOneEhentai_gallery) Where(conds ...field.Expr) *elementHasOneEhentai_gallery {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a elementHasOneEhentai_gallery) WithContext(ctx context.Context) *elementHasOneEhentai_gallery {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a elementHasOneEhentai_gallery) Model(m *dao.Element) *elementHasOneEhentai_galleryTx {
	return &elementHasOneEhentai_galleryTx{a.db.Model(m).Association(a.Name())}
}

type elementHasOneEhentai_galleryTx struct{ tx *gorm.Association }

func (a elementHasOneEhentai_galleryTx) Find() (result *dao.EhentaiGallery, err error) {
	return result, a.tx.Find(&result)
}

func (a elementHasOneEhentai_galleryTx) Append(values ...*dao.EhentaiGallery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a elementHasOneEhentai_galleryTx) Replace(values ...*dao.EhentaiGallery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a elementHasOneEhentai_galleryTx) Delete(values ...*dao.EhentaiGallery) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a elementHasOneEhentai_galleryTx) Clear() error {
	return a.tx.Clear()
}

func (a elementHasOneEhentai_galleryTx) Count() int64 {
	return a.tx.Count()
}

type elementHasManyEleFile struct {
	db *gorm.DB

	field.RelationField
}

func (a elementHasManyEleFile) Where(conds ...field.Expr) *elementHasManyEleFile {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a elementHasManyEleFile) WithContext(ctx context.Context) *elementHasManyEleFile {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a elementHasManyEleFile) Model(m *dao.Element) *elementHasManyEleFileTx {
	return &elementHasManyEleFileTx{a.db.Model(m).Association(a.Name())}
}

type elementHasManyEleFileTx struct{ tx *gorm.Association }

func (a elementHasManyEleFileTx) Find() (result []*dao.EleFile, err error) {
	return result, a.tx.Find(&result)
}

func (a elementHasManyEleFileTx) Append(values ...*dao.EleFile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a elementHasManyEleFileTx) Replace(values ...*dao.EleFile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a elementHasManyEleFileTx) Delete(values ...*dao.EleFile) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a elementHasManyEleFileTx) Clear() error {
	return a.tx.Clear()
}

func (a elementHasManyEleFileTx) Count() int64 {
	return a.tx.Count()
}

type elementManyToManyActor struct {
	db *gorm.DB

	field.RelationField
}

func (a elementManyToManyActor) Where(conds ...field.Expr) *elementManyToManyActor {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a elementManyToManyActor) WithContext(ctx context.Context) *elementManyToManyActor {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a elementManyToManyActor) Model(m *dao.Element) *elementManyToManyActorTx {
	return &elementManyToManyActorTx{a.db.Model(m).Association(a.Name())}
}

type elementManyToManyActorTx struct{ tx *gorm.Association }

func (a elementManyToManyActorTx) Find() (result []*dao.Actor, err error) {
	return result, a.tx.Find(&result)
}

func (a elementManyToManyActorTx) Append(values ...*dao.Actor) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a elementManyToManyActorTx) Replace(values ...*dao.Actor) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a elementManyToManyActorTx) Delete(values ...*dao.Actor) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a elementManyToManyActorTx) Clear() error {
	return a.tx.Clear()
}

func (a elementManyToManyActorTx) Count() int64 {
	return a.tx.Count()
}

type elementManyToManyAuthor struct {
	db *gorm.DB

	field.RelationField
}

func (a elementManyToManyAuthor) Where(conds ...field.Expr) *elementManyToManyAuthor {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a elementManyToManyAuthor) WithContext(ctx context.Context) *elementManyToManyAuthor {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a elementManyToManyAuthor) Model(m *dao.Element) *elementManyToManyAuthorTx {
	return &elementManyToManyAuthorTx{a.db.Model(m).Association(a.Name())}
}

type elementManyToManyAuthorTx struct{ tx *gorm.Association }

func (a elementManyToManyAuthorTx) Find() (result []*dao.Author, err error) {
	return result, a.tx.Find(&result)
}

func (a elementManyToManyAuthorTx) Append(values ...*dao.Author) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a elementManyToManyAuthorTx) Replace(values ...*dao.Author) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a elementManyToManyAuthorTx) Delete(values ...*dao.Author) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a elementManyToManyAuthorTx) Clear() error {
	return a.tx.Clear()
}

func (a elementManyToManyAuthorTx) Count() int64 {
	return a.tx.Count()
}

type elementManyToManyOrganization struct {
	db *gorm.DB

	field.RelationField
}

func (a elementManyToManyOrganization) Where(conds ...field.Expr) *elementManyToManyOrganization {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a elementManyToManyOrganization) WithContext(ctx context.Context) *elementManyToManyOrganization {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a elementManyToManyOrganization) Model(m *dao.Element) *elementManyToManyOrganizationTx {
	return &elementManyToManyOrganizationTx{a.db.Model(m).Association(a.Name())}
}

type elementManyToManyOrganizationTx struct{ tx *gorm.Association }

func (a elementManyToManyOrganizationTx) Find() (result []*dao.Organization, err error) {
	return result, a.tx.Find(&result)
}

func (a elementManyToManyOrganizationTx) Append(values ...*dao.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a elementManyToManyOrganizationTx) Replace(values ...*dao.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a elementManyToManyOrganizationTx) Delete(values ...*dao.Organization) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a elementManyToManyOrganizationTx) Clear() error {
	return a.tx.Clear()
}

func (a elementManyToManyOrganizationTx) Count() int64 {
	return a.tx.Count()
}

type elementManyToManyTagInfo struct {
	db *gorm.DB

	field.RelationField
}

func (a elementManyToManyTagInfo) Where(conds ...field.Expr) *elementManyToManyTagInfo {
	if len(conds) == 0 {
		return &a
	}

	exprs := make([]clause.Expression, 0, len(conds))
	for _, cond := range conds {
		exprs = append(exprs, cond.BeCond().(clause.Expression))
	}
	a.db = a.db.Clauses(clause.Where{Exprs: exprs})
	return &a
}

func (a elementManyToManyTagInfo) WithContext(ctx context.Context) *elementManyToManyTagInfo {
	a.db = a.db.WithContext(ctx)
	return &a
}

func (a elementManyToManyTagInfo) Model(m *dao.Element) *elementManyToManyTagInfoTx {
	return &elementManyToManyTagInfoTx{a.db.Model(m).Association(a.Name())}
}

type elementManyToManyTagInfoTx struct{ tx *gorm.Association }

func (a elementManyToManyTagInfoTx) Find() (result []*dao.TagInfo, err error) {
	return result, a.tx.Find(&result)
}

func (a elementManyToManyTagInfoTx) Append(values ...*dao.TagInfo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Append(targetValues...)
}

func (a elementManyToManyTagInfoTx) Replace(values ...*dao.TagInfo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Replace(targetValues...)
}

func (a elementManyToManyTagInfoTx) Delete(values ...*dao.TagInfo) (err error) {
	targetValues := make([]interface{}, len(values))
	for i, v := range values {
		targetValues[i] = v
	}
	return a.tx.Delete(targetValues...)
}

func (a elementManyToManyTagInfoTx) Clear() error {
	return a.tx.Clear()
}

func (a elementManyToManyTagInfoTx) Count() int64 {
	return a.tx.Count()
}

type elementDo struct{ gen.DO }

func (e elementDo) Debug() *elementDo {
	return e.withDO(e.DO.Debug())
}

func (e elementDo) WithContext(ctx context.Context) *elementDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e elementDo) ReadDB() *elementDo {
	return e.Clauses(dbresolver.Read)
}

func (e elementDo) WriteDB() *elementDo {
	return e.Clauses(dbresolver.Write)
}

func (e elementDo) Clauses(conds ...clause.Expression) *elementDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e elementDo) Returning(value interface{}, columns ...string) *elementDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e elementDo) Not(conds ...gen.Condition) *elementDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e elementDo) Or(conds ...gen.Condition) *elementDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e elementDo) Select(conds ...field.Expr) *elementDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e elementDo) Where(conds ...gen.Condition) *elementDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e elementDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *elementDo {
	return e.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (e elementDo) Order(conds ...field.Expr) *elementDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e elementDo) Distinct(cols ...field.Expr) *elementDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e elementDo) Omit(cols ...field.Expr) *elementDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e elementDo) Join(table schema.Tabler, on ...field.Expr) *elementDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e elementDo) LeftJoin(table schema.Tabler, on ...field.Expr) *elementDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e elementDo) RightJoin(table schema.Tabler, on ...field.Expr) *elementDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e elementDo) Group(cols ...field.Expr) *elementDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e elementDo) Having(conds ...gen.Condition) *elementDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e elementDo) Limit(limit int) *elementDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e elementDo) Offset(offset int) *elementDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e elementDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *elementDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e elementDo) Unscoped() *elementDo {
	return e.withDO(e.DO.Unscoped())
}

func (e elementDo) Create(values ...*dao.Element) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e elementDo) CreateInBatches(values []*dao.Element, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e elementDo) Save(values ...*dao.Element) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e elementDo) First() (*dao.Element, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Element), nil
	}
}

func (e elementDo) Take() (*dao.Element, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Element), nil
	}
}

func (e elementDo) Last() (*dao.Element, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Element), nil
	}
}

func (e elementDo) Find() ([]*dao.Element, error) {
	result, err := e.DO.Find()
	return result.([]*dao.Element), err
}

func (e elementDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dao.Element, err error) {
	buf := make([]*dao.Element, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e elementDo) FindInBatches(result *[]*dao.Element, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e elementDo) Attrs(attrs ...field.AssignExpr) *elementDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e elementDo) Assign(attrs ...field.AssignExpr) *elementDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e elementDo) Joins(fields ...field.RelationField) *elementDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e elementDo) Preload(fields ...field.RelationField) *elementDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e elementDo) FirstOrInit() (*dao.Element, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Element), nil
	}
}

func (e elementDo) FirstOrCreate() (*dao.Element, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Element), nil
	}
}

func (e elementDo) FindByPage(offset int, limit int) (result []*dao.Element, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e elementDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e elementDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e elementDo) Delete(models ...*dao.Element) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *elementDo) withDO(do gen.Dao) *elementDo {
	e.DO = *do.(*gen.DO)
	return e
}
