// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"javCrawl/internal/dal/dao"
)

func newActor(db *gorm.DB) actor {
	_actor := actor{}

	_actor.actorDo.UseDB(db)
	_actor.actorDo.UseModel(&dao.Actor{})

	tableName := _actor.actorDo.TableName()
	_actor.ALL = field.NewAsterisk(tableName)
	_actor.ID = field.NewInt32(tableName, "ID")
	_actor.NAME = field.NewString(tableName, "NAME")
	_actor.CREATEDTIME = field.NewTime(tableName, "CREATED_TIME")
	_actor.UPDATEDTIME = field.NewTime(tableName, "UPDATED_TIME")

	_actor.fillFieldMap()

	return _actor
}

type actor struct {
	actorDo

	ALL         field.Asterisk
	ID          field.Int32
	NAME        field.String
	CREATEDTIME field.Time
	UPDATEDTIME field.Time

	fieldMap map[string]field.Expr
}

func (a actor) Table(newTableName string) *actor {
	a.actorDo.UseTable(newTableName)
	return a.updateTableName(newTableName)
}

func (a actor) As(alias string) *actor {
	a.actorDo.DO = *(a.actorDo.As(alias).(*gen.DO))
	return a.updateTableName(alias)
}

func (a *actor) updateTableName(table string) *actor {
	a.ALL = field.NewAsterisk(table)
	a.ID = field.NewInt32(table, "ID")
	a.NAME = field.NewString(table, "NAME")
	a.CREATEDTIME = field.NewTime(table, "CREATED_TIME")
	a.UPDATEDTIME = field.NewTime(table, "UPDATED_TIME")

	a.fillFieldMap()

	return a
}

func (a *actor) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := a.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (a *actor) fillFieldMap() {
	a.fieldMap = make(map[string]field.Expr, 4)
	a.fieldMap["ID"] = a.ID
	a.fieldMap["NAME"] = a.NAME
	a.fieldMap["CREATED_TIME"] = a.CREATEDTIME
	a.fieldMap["UPDATED_TIME"] = a.UPDATEDTIME
}

func (a actor) clone(db *gorm.DB) actor {
	a.actorDo.ReplaceDB(db)
	return a
}

type actorDo struct{ gen.DO }

func (a actorDo) Debug() *actorDo {
	return a.withDO(a.DO.Debug())
}

func (a actorDo) WithContext(ctx context.Context) *actorDo {
	return a.withDO(a.DO.WithContext(ctx))
}

func (a actorDo) ReadDB() *actorDo {
	return a.Clauses(dbresolver.Read)
}

func (a actorDo) WriteDB() *actorDo {
	return a.Clauses(dbresolver.Write)
}

func (a actorDo) Clauses(conds ...clause.Expression) *actorDo {
	return a.withDO(a.DO.Clauses(conds...))
}

func (a actorDo) Returning(value interface{}, columns ...string) *actorDo {
	return a.withDO(a.DO.Returning(value, columns...))
}

func (a actorDo) Not(conds ...gen.Condition) *actorDo {
	return a.withDO(a.DO.Not(conds...))
}

func (a actorDo) Or(conds ...gen.Condition) *actorDo {
	return a.withDO(a.DO.Or(conds...))
}

func (a actorDo) Select(conds ...field.Expr) *actorDo {
	return a.withDO(a.DO.Select(conds...))
}

func (a actorDo) Where(conds ...gen.Condition) *actorDo {
	return a.withDO(a.DO.Where(conds...))
}

func (a actorDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *actorDo {
	return a.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (a actorDo) Order(conds ...field.Expr) *actorDo {
	return a.withDO(a.DO.Order(conds...))
}

func (a actorDo) Distinct(cols ...field.Expr) *actorDo {
	return a.withDO(a.DO.Distinct(cols...))
}

func (a actorDo) Omit(cols ...field.Expr) *actorDo {
	return a.withDO(a.DO.Omit(cols...))
}

func (a actorDo) Join(table schema.Tabler, on ...field.Expr) *actorDo {
	return a.withDO(a.DO.Join(table, on...))
}

func (a actorDo) LeftJoin(table schema.Tabler, on ...field.Expr) *actorDo {
	return a.withDO(a.DO.LeftJoin(table, on...))
}

func (a actorDo) RightJoin(table schema.Tabler, on ...field.Expr) *actorDo {
	return a.withDO(a.DO.RightJoin(table, on...))
}

func (a actorDo) Group(cols ...field.Expr) *actorDo {
	return a.withDO(a.DO.Group(cols...))
}

func (a actorDo) Having(conds ...gen.Condition) *actorDo {
	return a.withDO(a.DO.Having(conds...))
}

func (a actorDo) Limit(limit int) *actorDo {
	return a.withDO(a.DO.Limit(limit))
}

func (a actorDo) Offset(offset int) *actorDo {
	return a.withDO(a.DO.Offset(offset))
}

func (a actorDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *actorDo {
	return a.withDO(a.DO.Scopes(funcs...))
}

func (a actorDo) Unscoped() *actorDo {
	return a.withDO(a.DO.Unscoped())
}

func (a actorDo) Create(values ...*dao.Actor) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Create(values)
}

func (a actorDo) CreateInBatches(values []*dao.Actor, batchSize int) error {
	return a.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (a actorDo) Save(values ...*dao.Actor) error {
	if len(values) == 0 {
		return nil
	}
	return a.DO.Save(values)
}

func (a actorDo) First() (*dao.Actor, error) {
	if result, err := a.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Actor), nil
	}
}

func (a actorDo) Take() (*dao.Actor, error) {
	if result, err := a.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Actor), nil
	}
}

func (a actorDo) Last() (*dao.Actor, error) {
	if result, err := a.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Actor), nil
	}
}

func (a actorDo) Find() ([]*dao.Actor, error) {
	result, err := a.DO.Find()
	return result.([]*dao.Actor), err
}

func (a actorDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dao.Actor, err error) {
	buf := make([]*dao.Actor, 0, batchSize)
	err = a.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (a actorDo) FindInBatches(result *[]*dao.Actor, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return a.DO.FindInBatches(result, batchSize, fc)
}

func (a actorDo) Attrs(attrs ...field.AssignExpr) *actorDo {
	return a.withDO(a.DO.Attrs(attrs...))
}

func (a actorDo) Assign(attrs ...field.AssignExpr) *actorDo {
	return a.withDO(a.DO.Assign(attrs...))
}

func (a actorDo) Joins(fields ...field.RelationField) *actorDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Joins(_f))
	}
	return &a
}

func (a actorDo) Preload(fields ...field.RelationField) *actorDo {
	for _, _f := range fields {
		a = *a.withDO(a.DO.Preload(_f))
	}
	return &a
}

func (a actorDo) FirstOrInit() (*dao.Actor, error) {
	if result, err := a.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Actor), nil
	}
}

func (a actorDo) FirstOrCreate() (*dao.Actor, error) {
	if result, err := a.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dao.Actor), nil
	}
}

func (a actorDo) FindByPage(offset int, limit int) (result []*dao.Actor, count int64, err error) {
	result, err = a.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = a.Offset(-1).Limit(-1).Count()
	return
}

func (a actorDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = a.Count()
	if err != nil {
		return
	}

	err = a.Offset(offset).Limit(limit).Scan(result)
	return
}

func (a actorDo) Scan(result interface{}) (err error) {
	return a.DO.Scan(result)
}

func (a actorDo) Delete(models ...*dao.Actor) (result gen.ResultInfo, err error) {
	return a.DO.Delete(models)
}

func (a *actorDo) withDO(do gen.Dao) *actorDo {
	a.DO = *do.(*gen.DO)
	return a
}
