// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"javCrawl/internal/dal/dao"
)

func newEleAuthorRe(db *gorm.DB) eleAuthorRe {
	_eleAuthorRe := eleAuthorRe{}

	_eleAuthorRe.eleAuthorReDo.UseDB(db)
	_eleAuthorRe.eleAuthorReDo.UseModel(&dao.EleAuthorRe{})

	tableName := _eleAuthorRe.eleAuthorReDo.TableName()
	_eleAuthorRe.ALL = field.NewAsterisk(tableName)
	_eleAuthorRe.ID = field.NewInt32(tableName, "ID")
	_eleAuthorRe.ELEID = field.NewInt64(tableName, "ELE_ID")
	_eleAuthorRe.AUTHORID = field.NewInt32(tableName, "AUTHOR_ID")

	_eleAuthorRe.fillFieldMap()

	return _eleAuthorRe
}

type eleAuthorRe struct {
	eleAuthorReDo

	ALL      field.Asterisk
	ID       field.Int32
	ELEID    field.Int64
	AUTHORID field.Int32

	fieldMap map[string]field.Expr
}

func (e eleAuthorRe) Table(newTableName string) *eleAuthorRe {
	e.eleAuthorReDo.UseTable(newTableName)
	return e.updateTableName(newTableName)
}

func (e eleAuthorRe) As(alias string) *eleAuthorRe {
	e.eleAuthorReDo.DO = *(e.eleAuthorReDo.As(alias).(*gen.DO))
	return e.updateTableName(alias)
}

func (e *eleAuthorRe) updateTableName(table string) *eleAuthorRe {
	e.ALL = field.NewAsterisk(table)
	e.ID = field.NewInt32(table, "ID")
	e.ELEID = field.NewInt64(table, "ELE_ID")
	e.AUTHORID = field.NewInt32(table, "AUTHOR_ID")

	e.fillFieldMap()

	return e
}

func (e *eleAuthorRe) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := e.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (e *eleAuthorRe) fillFieldMap() {
	e.fieldMap = make(map[string]field.Expr, 3)
	e.fieldMap["ID"] = e.ID
	e.fieldMap["ELE_ID"] = e.ELEID
	e.fieldMap["AUTHOR_ID"] = e.AUTHORID
}

func (e eleAuthorRe) clone(db *gorm.DB) eleAuthorRe {
	e.eleAuthorReDo.ReplaceDB(db)
	return e
}

type eleAuthorReDo struct{ gen.DO }

func (e eleAuthorReDo) Debug() *eleAuthorReDo {
	return e.withDO(e.DO.Debug())
}

func (e eleAuthorReDo) WithContext(ctx context.Context) *eleAuthorReDo {
	return e.withDO(e.DO.WithContext(ctx))
}

func (e eleAuthorReDo) ReadDB() *eleAuthorReDo {
	return e.Clauses(dbresolver.Read)
}

func (e eleAuthorReDo) WriteDB() *eleAuthorReDo {
	return e.Clauses(dbresolver.Write)
}

func (e eleAuthorReDo) Clauses(conds ...clause.Expression) *eleAuthorReDo {
	return e.withDO(e.DO.Clauses(conds...))
}

func (e eleAuthorReDo) Returning(value interface{}, columns ...string) *eleAuthorReDo {
	return e.withDO(e.DO.Returning(value, columns...))
}

func (e eleAuthorReDo) Not(conds ...gen.Condition) *eleAuthorReDo {
	return e.withDO(e.DO.Not(conds...))
}

func (e eleAuthorReDo) Or(conds ...gen.Condition) *eleAuthorReDo {
	return e.withDO(e.DO.Or(conds...))
}

func (e eleAuthorReDo) Select(conds ...field.Expr) *eleAuthorReDo {
	return e.withDO(e.DO.Select(conds...))
}

func (e eleAuthorReDo) Where(conds ...gen.Condition) *eleAuthorReDo {
	return e.withDO(e.DO.Where(conds...))
}

func (e eleAuthorReDo) Exists(subquery interface{ UnderlyingDB() *gorm.DB }) *eleAuthorReDo {
	return e.Where(field.CompareSubQuery(field.ExistsOp, nil, subquery.UnderlyingDB()))
}

func (e eleAuthorReDo) Order(conds ...field.Expr) *eleAuthorReDo {
	return e.withDO(e.DO.Order(conds...))
}

func (e eleAuthorReDo) Distinct(cols ...field.Expr) *eleAuthorReDo {
	return e.withDO(e.DO.Distinct(cols...))
}

func (e eleAuthorReDo) Omit(cols ...field.Expr) *eleAuthorReDo {
	return e.withDO(e.DO.Omit(cols...))
}

func (e eleAuthorReDo) Join(table schema.Tabler, on ...field.Expr) *eleAuthorReDo {
	return e.withDO(e.DO.Join(table, on...))
}

func (e eleAuthorReDo) LeftJoin(table schema.Tabler, on ...field.Expr) *eleAuthorReDo {
	return e.withDO(e.DO.LeftJoin(table, on...))
}

func (e eleAuthorReDo) RightJoin(table schema.Tabler, on ...field.Expr) *eleAuthorReDo {
	return e.withDO(e.DO.RightJoin(table, on...))
}

func (e eleAuthorReDo) Group(cols ...field.Expr) *eleAuthorReDo {
	return e.withDO(e.DO.Group(cols...))
}

func (e eleAuthorReDo) Having(conds ...gen.Condition) *eleAuthorReDo {
	return e.withDO(e.DO.Having(conds...))
}

func (e eleAuthorReDo) Limit(limit int) *eleAuthorReDo {
	return e.withDO(e.DO.Limit(limit))
}

func (e eleAuthorReDo) Offset(offset int) *eleAuthorReDo {
	return e.withDO(e.DO.Offset(offset))
}

func (e eleAuthorReDo) Scopes(funcs ...func(gen.Dao) gen.Dao) *eleAuthorReDo {
	return e.withDO(e.DO.Scopes(funcs...))
}

func (e eleAuthorReDo) Unscoped() *eleAuthorReDo {
	return e.withDO(e.DO.Unscoped())
}

func (e eleAuthorReDo) Create(values ...*dao.EleAuthorRe) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Create(values)
}

func (e eleAuthorReDo) CreateInBatches(values []*dao.EleAuthorRe, batchSize int) error {
	return e.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (e eleAuthorReDo) Save(values ...*dao.EleAuthorRe) error {
	if len(values) == 0 {
		return nil
	}
	return e.DO.Save(values)
}

func (e eleAuthorReDo) First() (*dao.EleAuthorRe, error) {
	if result, err := e.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*dao.EleAuthorRe), nil
	}
}

func (e eleAuthorReDo) Take() (*dao.EleAuthorRe, error) {
	if result, err := e.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*dao.EleAuthorRe), nil
	}
}

func (e eleAuthorReDo) Last() (*dao.EleAuthorRe, error) {
	if result, err := e.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*dao.EleAuthorRe), nil
	}
}

func (e eleAuthorReDo) Find() ([]*dao.EleAuthorRe, error) {
	result, err := e.DO.Find()
	return result.([]*dao.EleAuthorRe), err
}

func (e eleAuthorReDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*dao.EleAuthorRe, err error) {
	buf := make([]*dao.EleAuthorRe, 0, batchSize)
	err = e.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (e eleAuthorReDo) FindInBatches(result *[]*dao.EleAuthorRe, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return e.DO.FindInBatches(result, batchSize, fc)
}

func (e eleAuthorReDo) Attrs(attrs ...field.AssignExpr) *eleAuthorReDo {
	return e.withDO(e.DO.Attrs(attrs...))
}

func (e eleAuthorReDo) Assign(attrs ...field.AssignExpr) *eleAuthorReDo {
	return e.withDO(e.DO.Assign(attrs...))
}

func (e eleAuthorReDo) Joins(fields ...field.RelationField) *eleAuthorReDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Joins(_f))
	}
	return &e
}

func (e eleAuthorReDo) Preload(fields ...field.RelationField) *eleAuthorReDo {
	for _, _f := range fields {
		e = *e.withDO(e.DO.Preload(_f))
	}
	return &e
}

func (e eleAuthorReDo) FirstOrInit() (*dao.EleAuthorRe, error) {
	if result, err := e.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*dao.EleAuthorRe), nil
	}
}

func (e eleAuthorReDo) FirstOrCreate() (*dao.EleAuthorRe, error) {
	if result, err := e.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*dao.EleAuthorRe), nil
	}
}

func (e eleAuthorReDo) FindByPage(offset int, limit int) (result []*dao.EleAuthorRe, count int64, err error) {
	result, err = e.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = e.Offset(-1).Limit(-1).Count()
	return
}

func (e eleAuthorReDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = e.Count()
	if err != nil {
		return
	}

	err = e.Offset(offset).Limit(limit).Scan(result)
	return
}

func (e eleAuthorReDo) Scan(result interface{}) (err error) {
	return e.DO.Scan(result)
}

func (e eleAuthorReDo) Delete(models ...*dao.EleAuthorRe) (result gen.ResultInfo, err error) {
	return e.DO.Delete(models)
}

func (e *eleAuthorReDo) withDO(do gen.Dao) *eleAuthorReDo {
	e.DO = *do.(*gen.DO)
	return e
}
